server:
  port: 9002
spring:
#  datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/house?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
#      username: root
#      password: zzq845211164
#      initialize: true
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://47.103.88.133:3306/house?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
        username: zzq
        password: zzq845211164
        initialize: true
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
   mapper-locations: classpath:mapper/*.xml #注意：一定要对应mapper映射xml文件的所在路径
   type-aliases-package: com.house.pojo # 注意：对应实体类的路径
   #mybatis.configuration.map-underscore-to-camel-case=true开启驼峰命名识别
   configuration:
     map-underscore-to-camel-case: true
## jwt 令牌的相关配置
jwt:
  secret: zhangbo #私钥
  expiration: 21600000 #过期时间，6个小时
  header: Authorization #请求头部存放的 token 令牌
  refresh_expiration: 651000000 #刷新 token 的过期时间 7 天

#redis配置
redis:
  #服务器地址
  host: 120.77.80.135
  #端口
  port: 6379
  #redis密码
  password: XXXXXX
  #超时时间
  timeout: 1209600000ms
  lettuce:
    pool:
      #最大链接数，默认8
      max-active: 8
      #最大连接阻塞等待时间，默认-1
      max-wait: 10000ms
      #最大空闲连接，默认8
      max-idle: 200
      #最小空闲连接，默认0
      min-idle: 5





